#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Apr 11, 2025 06:05:45 PM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import Win

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    root.iconbitmap("icon.ico")
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Win.Toplevel1(_top1)
    root.mainloop()

if __name__ == '__main__':
    Win.start_up()




